routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin', 'adminController');
Route::resource('outlets','OutletController');
Route::resource('paket','paketController');
Route::resource('member','MemberController');
Route::resource('transaksi','transaksiController');
Route::resource('pengguna','pengguna');
// Route::get('paket/{id_outlet}', 'paketController@create')->name('createPaket');

app/transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class transaksi extends Model
{ 
    protected $table ='transaksi';
	
	protected $primaryKey ='id_transaksi';

    protected $fillable = [
    	'id_outlet','kode_invoice','id_member','tgl','status','dibayar','id_user','id_paket'
    ];

    public function user(){
    	return $this->belongsTo('App\User','id_user');
    }
    public function outlet(){
    	return $this->belongsTo('App\Outlet','id_outlet');
    }
    public function member(){
    	return $this->belongsTo('App\member','id_member');
    }

     public function paket(){
        return $this->belongsTo('App\paket','id_paket');
    }

    public function scopeInvoice()
    {
        $latest = transaksi::latest()->first();

        if (! $latest) {
            return 'arm0001';
        }

        $string = preg_replace("/[^0-9\.]/", '', $latest->kode_invoice);

        return 'arm' . sprintf('%04d', $string+1);
    }

}

app/Http/Controllers/transaksiController.php
<?php

namespace App\Http\Controllers;

use App\transaksi;
use App\member;
use App\Outlet;
use App\User;
use App\paket;

use Illuminate\Http\Request;
use Carbon\carbon;

class transaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksi = transaksi::latest()->paginate(10);
        return view('transaksi.index',compact('transaksi'))
            ->with('i',(request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $date = Carbon::now();
        $tgl = $date;
        $status = 'baru';
        $user = auth()->user()->id;
        $outlet = Outlet::get();
        $invoice = transaksi::Invoice();
        $member = member::get();

        $paket = paket::get();
        return view('transaksi.create',compact('tgl','user','invoice','member','outlet','paket','status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

         transaksi::create([
            'id_user'     => $data['id_user'],
            'id_outlet'   => $data['id_outlet'],
            'kode_invoice' => $data['kode_invoice'], 
            'tgl'         => $data['tgl'],
            'status'         => $data['status'],
            'id_member'         => $data['id_member'],
            'dibayar'         => $data['dibayar'],
            'id_paket'         => $data['id_paket'],
        ]);
        return redirect()->route('transaksi.index')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function show(transaksi $transaksi)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit(transaksi $transaksi)
    {
        $date = Carbon::now();
        $tgl = $date;
        $status = 'baru';
        $user = auth()->user()->id;
        $outlet = Outlet::get();
        $invoice = transaksi::Invoice();
        $member = member::get();

        $paket = paket::get();
        return view('transaksi.edit',compact('tgl','user','invoice','member','outlet','paket','status','transaksi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, transaksi $transaksi)
    {
        $data = $request->all();
        $id =  $transaksi->id_transaksi;
         transaksi::where('id_transaksi', $id)->update([
            'status'         => $data['status'],
            'dibayar'         => $data['dibayar'],
        ]);
         return redirect()->route('transaksi.index')->with('success', 'Data Added successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function destroy(transaksi $transaksi)
    {
        $transaksi->delete();

        return redirect()->route('transaksi.index')
                        ->with('success','transaksi Berhasil di Delete');
    }
}

resources/views/transaksi/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">

		<div class="col-sm-12 float-left">
			
			<a class="btn btn-primary" href="{{ URL::previous() }}" > Back</a>

		</div>
		
		
		<div class="text-center txt-tittle">
			
			<h2>Entry transaksi</h2>

		</div>

	</div>


</div>
<div class="text-center txt-outlet">
	<div class="col-xm-12">
		@foreach($outlet->where('id_outlet',auth()->user()->id_outlet) as $toko)
		<h1>" {{ $toko->nama_outlet }} "</h1>
		@endforeach
	</div>

</div>

@if ($errors->any())



<div class="alert alert-danger">
	
	<strong>Upss! </strong> Ada yang salah dari inputanmu. <br><br>

	<ul>
		
		@foreach ($errors->all() as $error)

		<li>{{ $error }}</li>

		@endforeach

	</ul>

</div>

@endif



<form action="{{ route('transaksi.store') }}" method="POST">
	
	@csrf

	<input type="text" class="none" id="kode_invoice" name="kode_invoice" value="{{$invoice}}">
	<input type="text" class="none" id="tgl" name="tgl" value="{{$tgl->toDateString()}}">
	<input type="text" class="none" id="status" name="status" value="{{$status}}">
	<input type="text" class="none" id="id_user" name="id_user" value="{{$user}}">
	<input type="text" class="none" id="id_outlet" name="id_outlet" value="{{ auth()->user()->id_outlet }}">



	<div class="row">
		
		<div class="col-xs-12 col-sm-12 col-md-11">
			
			<div class="form-group">

				<div class="col-sm-12 txt-nama">
				
				<h2>Nama Member :</h2>
				</div>

				<div class="btn-newmem">
					<a href="{{ route('member.create') }}" class="btn btn-info mb-3" style="color: #fff">New Member</a>
				</div>

				<select name="id_member" id="id_member" class="form-control name-form">
					@foreach($member as $m)
					<option value="{{$m->id_member}}" >{{ $m->nama }}</option>
					@endforeach
				</select>
				

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11">
			
			<div class="form-group">

				<div class="col-sm-12 txt-nama">
				
				<h2>Paket :</h2>

				</div>

				<select name="id_paket" id="id_paket" class="form-control name-form">
					@foreach($paket->where('id_outlet', auth()->user()->id_outlet) as $o)
					<option value="{{ $o->id_paket }}">{{ $o->nama_paket }}</option>
					@endforeach
				</select>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11">
			
			<div class="form-group">

				<div class="col-sm-12 txt-nama">
				
				<h2>Status Pembayaran :</h2>

				</div>

				<select name="dibayar" id="dibayar" class="form-control name-form">
					<option value="1">Dibayar</option>
					<option value="0">Belum Dibayar</option>
				</select>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11 text-center">

			<button type="submit" class="btn btn-primary btn-submit mt-3">Entry Transaksi</button>


		</div>

	</div>

</form>

</div>
@endsection

resources/views/transaksi/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
		<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">

		<div class="col-sm-12 float-left mt-3">
			
			<a class="btn btn-primary" href="{{ URL::previous() }}" > Back</a>

		</div>
		
		
		<div class="text-center txt-tittle">
			
			<h2>Entry transaksi</h2>

		</div>

	</div>

</div>
<div class="text-center txt-outlet">
	<div class="col-xm-12">
		@foreach($outlet->where('id_outlet',auth()->user()->id_outlet) as $toko)
		<h1>" {{ $toko->nama_outlet }} "</h1>
		@endforeach
	</div>
</div>

@if ($errors->any())

<div class="alert alert-danger">
	
	<strong>Upss! </strong> Ada yang salah dari inputanmu. <br><br>

	<ul>
		
		@foreach ($errors->all() as $error)

		<li>{{ $error }}</li>

		@endforeach

	</ul>

</div>

@endif

<form action="{{ route('transaksi.update',$transaksi->id_transaksi) }}" method="POST">
	
	@csrf
	@method('PUT')

	<div class="row">
		
		<div class="col-xs-12 col-sm-12 col-md-12">
			
			<div class="form-group">

				<div class="col-sm-12 txt-nama">
				
				<h2>Nama Member :</h2>

			</div>

			<div class="edit-txt-name">
				
				<h2 type="text" id="id_member" name="id_member" value="" class="">{{ $transaksi->member->nama ?? '' }}</h2>
				</div>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-12">
			
			<div class="col-sm-12 txt-nama">
				
				<h2>Paket 	:</h2>

				<div class="edit-txt-paket">

					<h2 type="text" id="id_paket" name="id_paket" value="" >{{ $transaksi->paket->nama_paket }} </h2>
				</div>
			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11">
			
			<div class="col-sm-12 txt-nama mt-2">
				
				<h2>Status Pembayaran :</h2>

				<select name="dibayar" id="dibayar" class="form-control">
					<option value="1">Dibayar</option>
					<option value="0">Belum dibayar</option>
				</select>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11">
			
			<div class="col-sm-12 txt-nama mt-4">
				
				<h2>Status Pengerjaan :</h2>

				<select name="status" id="status" class="form-control">
					<option value="baru">Baru</option>
					<option value="selesai">Selesai</option>
					<option value="diambil">Diambil</option>
				</select>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-11 text-center">

			<button type="submit" class="btn btn-primary mt-5 btn-submit">Edit Transaksi</button>


		</div>

	</div>

</form>

</div>
@endsection

resources/views/transaksi/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">	
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">
		<div class="pull-left">
			<div class="title">

			<h2>Data transaksi</h2>
		</div>
		<div class="pull-right">
			<a class="btn btn-success" href="{{ route('transaksi.create') }}"> Buat transaksi Baru</a>
		</div>
		</div>
	</div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">

	<tr class="table-color-header">

		<th>No</th>
		<th>Kode Invoice</th>
		<th>Nama member</th>
		<th>Nama Outlet</th>
		<th>Paket</th>
		<th>Harga</th>
		<th>tgl</th>
		<th>Status</th>
		<th>Pembayaran</th>
		<th>Pelayan</th>
		<th width="280px">Action</th>
	</tr>
	@foreach ($transaksi as $transaksis)

	<tr>
		<td>{{ ++$i }}</td>
		<td>{{ $transaksis->kode_invoice }}</td>
		<td>{{ $transaksis->member->nama ?? ''}}</td>
		<td>{{ $transaksis->outlet->nama_outlet }}</td>
		<td>{{ $transaksis->paket->nama_paket }}</td>
		<td>{{ $transaksis->paket->harga }}</td>
		<td>{{ $transaksis->tgl }}</td>
		<td>{{ $transaksis->status }}</td>
		@if($transaksis->dibayar == '1')
		<td>Sudah Dibayar</td>
		@else
		<td>Belum Dibayar</td>
		@endif
		<td>{{ $transaksis->user->nama_user }}</td>
	
	<td>
		<form class="center" action="{{ route('transaksi.destroy',$transaksis->id_transaksi) }}" method="POST">

			<a class="btn btn-primary" href="{{ route('transaksi.edit', $transaksis->id_transaksi) }}" >Edit</a>

			@csrf
			@method('DELETE')

			<button type="submit" class="btn btn-danger">Delete</button>

			

		</form>
		
	</td>

	</tr>

	@endforeach

</table>

{!! $transaksi->links() !!}

</div>

@endsection