routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin', 'adminController');
Route::resource('outlets','OutletController');
Route::resource('paket','paketController');
Route::resource('member','MemberController');
Route::resource('transaksi','transaksiController');
Route::resource('pengguna','pengguna');
// Route::get('paket/{id_outlet}', 'paketController@create')->name('createPaket');

app/Http/Controllers/Pengguna.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Outlet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class Pengguna extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::latest()->paginate(10);
        return view('pengguna.index', compact('user'))
                ->with('i',(request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $outlet = Outlet::get();
        return view('auth.register',compact('outlet'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_user' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'role'  => 'required',
            'id_outlet' => 'required',
        ]);

        if ($request->role == 'admin') {
            $create = array(
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'id_outlet' => $request->id_outlet,            
                'isAdmin' => '1',
            );

                User::create($create);
        }

        else if($request->role == 'kasir'){
            $create = array(
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'id_outlet' => $request->id_outlet,           
                'isKasir' => '1',
            );
                 User::create($create);
        }

        else if($request->role == 'owner'){
                $create = array(
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'id_outlet' => $request->id_outlet,            
                'isOwner' => '1',
            );
                User::create($create);
        }
        else{
            return redirect()->route('register');
        }

        
        return redirect()->route('pengguna.index')
        ->with('succes','user anda sudah berhasil ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findorfail($id);
        $outlet = Outlet::get();
        return view('pengguna.edit',compact('user','outlet'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'id' =>'required',
            'nama_user' => 'required',
            'email' => 'required',
            'role' => 'required',
            'id_outlet' => 'required'
        ]);

        if ($request->role == 'admin') {
            $create = array(
                'id' => $request->id,
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'id_outlet' => $request->id_outlet,            
                'isAdmin' => '1',
            );

                User::whereId($request->id)->update($create);
        }

        else if($request->role == 'kasir'){
            $create = array(
                'id' => $request->id,
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'id_outlet' => $request->id_outlet,           
                'isKasir' => '1',
            );
                 User::whereId($request->id)->update($create);
        }

        else if($request->role == 'owner'){
                $create = array(
                'id' => $request->id,
                'nama_user' => $request->nama_user,
                'email' => $request->email,
                'id_outlet' => $request->id_outlet,            
                'isOwner' => '1',
            );
                User::whereId($request->id)->update($create);
        }
        else{
            return redirect()->route('register');
        }

        
        return redirect()->route('pengguna.index')
        ->with('succes','user anda sudah berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('pengguna.index')
                        ->with('success','User Berhasil di Delete');    }
}

resources/views/pengguna/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
             <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

                <div class="card-body card-register-edit">

                    <form method="POST" action="{{ route('pengguna.update',$user->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="row text-center">
                            <div class="col-sm-12 tittle">
                                <h1>EDIT PENGGUNA</h1>
                                <div class="underline-tittle-edit-pengguna"></div>
                            </div>
                        </div>
                        <input type="text" class="none" name="id" value="{{ $user->id }}">
                        <div class="form-group row">
                            <label for="user-name" class="label-regis" >&nbsp;Nama</label>
                            <div class="col-md-8 mt-3 form-nama-edit">
                                <input id="nama_user" type="text" class="form-control @error('nama_user') is-invalid @enderror" name="nama_user" value="{{ $user->nama_user }}" required autocomplete="name" placeholder="Masukan Nama" autofocus>

                                @error('nama_user')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="user-name" class="label-regis" >&nbsp;Email</label>
                            <div class="col-md-8 mt-3 form-email-edit">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" placeholder="Masukan Email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="" class="label-regis">&nbsp;Role</label>

                            <div class="col-md-8 mt-3">
                                <select name="role" id="" class="form-control form-role-edit">
                                    <option value="">Pilih Role Akun</option>
                                    <option value="admin" {{ $user->isAdmin == 1 ? 'selected' : '' }}>Admin</option>
                                    <option value="owner" {{ $user->isOwner == 1 ? 'selected' : '' }}>Owner</option>
                                    <option value="kasir" {{ $user->isKasir == 1 ? 'selected' : '' }}>Kasir</option>
                                </select>
                            </div>

                        </div>

                        <div class="form-group row">
                            <label for="" class="label-regis">&nbsp;Outlet</label>

                            <div class="col-md-8 mt-3">
                                <select name="id_outlet" id="" class="form-control form-outlet-edit">
                                    @foreach($outlet->where('id_outlet', $user->id_outlet) as $o)
                                    <option value="{{$o->id_outlet}}">{{$o->nama_outlet}}</option>
                                    @endforeach
                                    <div class="divider"></div>
                                    @foreach($outlet as $o)
                                    <option value="{{$o->id_outlet}}">{{$o->nama_outlet}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>

                        </div>

                        <div class="form-group row mt-2">
                            <div class="col-md-12 ">
                                <button type="submit" class="btn btn-primary btn-regis">
                                    {{ __('E D I T') }}
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pengguna/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">	
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">
		<div class="pull-left">
			<div class="title">

			<h2>Data pengguna</h2>
		</div>
		<div class="pull-right">
			<a class="btn btn-success" href="{{ route('pengguna.create') }}"> Buat pengguna Baru</a>
		</div>
		</div>
	</div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">

	<tr class="table-color-header">

		<th>No</th>
		<th>Username</th>
		<th>Email</th>
		<th>Nama Outlet</th>
		<th>Role</th>
		<th width="280px">Action</th>
	</tr>
	@foreach ($user as $users)

	<tr>
		<td>{{ ++$i }}</td>
		<td>{{ $users->nama_user }}</td>
		<td>{{ $users->email }}</td>
		<td>{{ $users->outlet->nama_outlet }}</td>
		@if($users->isAdmin == '1')
		<td>Admin</td>
		@elseif($users->isKasir == '1')
		<td>Kasir</td>
		@elseif($users->isOwner == '1')
		<td>Owner</td>
		@else
		<td>belum memiliki role</td>
		@endif
	
	<td>
		<form class="center" action="{{ route('pengguna.destroy',$users->id) }}" method="POST">

			<a class="btn btn-primary" href="{{ route('pengguna.edit', $users->id) }}" >Edit</a>

			@csrf
			@method('DELETE')

			<button type="submit" class="btn btn-danger">Delete</button>

			

		</form>
		
	</td>

	</tr>

	@endforeach

</table>

{!! $user->links() !!}

</div>

@endsection