routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/admin', 'adminController');
Route::resource('outlets','OutletController');
Route::resource('paket','paketController');
Route::resource('member','MemberController');
Route::resource('transaksi','transaksiController');
Route::resource('pengguna','pengguna');
// Route::get('paket/{id_outlet}', 'paketController@create')->name('createPaket');

app/Outlet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Outlet extends Model
{
	protected $table ='outlet';
	
	protected $primaryKey ='id_outlet';

    protected $fillable = [
    	'nama_outlet','alamat','no_telp'
    ];

    public function paket(){
    	return $this->hasMany('App\paket','id_outlet');
    }

    public function transaksi(){
    	return $this->hasMany('App\paket','id_outlet');
    }
    

}

app/Http/Controllers/OutletController.php
<?php

namespace App\Http\Controllers;

use App\Outlet;
use App\paket;
use Illuminate\Http\Request;

class OutletController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $outlets = Outlet::latest()->paginate(5);

        return view('outlet.index',compact('outlets'))
            ->with('i',(request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('outlet.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_outlet' => 'required',

            'alamat' => 'required',

            'no_telp' => 'required',
        ]);

        Outlet::create($request->all());

        return redirect()->route('outlets.index')
                        ->with('success','Outlet Telah Ditambahkan !.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Http\Response
     */
    public function show(Outlet $outlet) 
    {
        $paket = paket::get();
        return view('outlet.show',compact('outlet','paket'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Http\Response
     */
    public function edit(Outlet $outlet)
    {
         return view('outlet.edit',compact('outlet'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Outlet $outlet)
    {
        $request->validate([
            'nama_outlet' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
        ]);

        $outlet->update($request->all());

        return redirect()->route('outlets.index')
                        ->with('success','Outlet Berhasil Diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Http\Response
     */
    public function destroy(Outlet $outlet)
    {
        $outlet->delete();

        return redirect()->route('outlets.index')
                        ->with('success','Outlet Berhasil di Delete');
    }
}

resources/views/outlet/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">
		
		<div class="text-center txt-tittle">
			
			<h2>Tambah Outlet Baru</h2>

		</div>

		<div class="pull-right">
			
			<a class="btn btn-primary" href="{{ route('outlets.index') }}" > Back</a>

		</div>

	</div>

</div>

@if ($errors->any())

<div class="alert alert-danger">
	
	<strong>Upss! </strong> Ada yang salah dari inputanmu. <br><br>

	<ul>
		
		@foreach ($errors->all() as $error)

		<li>{{ $error }}</li>

		@endforeach

	</ul>

</div>

@endif

<form action="{{ route('outlets.store') }}" method="POST">
	
	@csrf

	<div class="row">
		
		<div class="col-xs-12 col-sm-12 col-md-12 mt-4">
			
			<div class="form-group txt-nama">
				
				<h2>Nama Outlet :</h2>

				<input type="text" name="nama_outlet" class="form-control" placeholder="Masukan Nama Outlet">

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-12">
			
			<div class="form-group txt-nama">
				
				<h2>Alamat :</h2>

				<textarea class="form-control" style="height:150px" name="alamat" placeholder="Masukan Alamat"></textarea>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-12">

			<div class="form-group txt-nama">
				<h2>No Telepon :</h2>

				<input type="text" name="no_telp" class="form-control" placeholder="Masukan No Telepon">

			</div>
			
		</div>

		<div class="col-xs-12 col-sm-12 col-md-12 text-center">

			<button type="submit" class="btn btn-primary btn-submit-edit">Tambah Outlet</button>


		</div>

	</div>

</form>

</div>
@endsection

resources/views/outlet/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	
	<div class="col-lg-12 margin-tb">
		
	<div class="text-center txt-tittle">
		
		<h2>Edit Outlet</h2>

	</div>

		<div class="pull-right">
		
			<a class="btn btn-primary" href="{{ route('outlets.index') }}">Back</a>

		</div>

	</div>

</div>

@if ($errors->any())

<div class="alert alert-danger">
	
	<strong>Uppss!</strong> Ada yang salah dari inputanmu <br><br>

	<ul>
		
		@foreach ($errors->all() as $error)

			<li>{{ $error }}</li>

		@endforeach

	</ul>

</div>

@endif

<form action="{{ route('outlets.update', $outlet->id_outlet) }}" method="POST">
	
	@csrf

	@method('PUT')

	<div class="row">
		
		<div class="col-xs-12 col-sm-12 col-md-12 mt-4">
			
			<div class="form-group txt-nama">
				
				<h2>Nama Outlet :</h2>

				<input type="text" name="nama_outlet" value="{{$outlet->nama_outlet}}" class="form-control" placeholder="Nama Outlet">

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-12">
			
			<div class="form-group txt-nama">
				
				<h2>Alamat :</h2>

				<textarea class="form-control" style="height:150px" name="alamat" placeholder="Alamat">{{$outlet->alamat}}</textarea>

			</div>

		</div>

		<div class="col-xs-12 col-sm-12 col-md-12">

			<div class="form-group txt-nama">
				<h2>No Telepon :</h2>

				<input type="text" name="no_telp" value="{{ $outlet->no_telp }}" class="form-control" placeholder="No Telepon">

			</div>
			
		</div>

		<div class="col-xs-12 col-sm-12 col-md-12 text-center">

			<button type="submit" class="btn btn-primary btn-submit-edit">Edit Outlet</button>


		</div>

	</div>
	

</form>
</div>
@endsection

resources/views/outlet/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">	
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	<div class="col-lg-12 margin-tb">
		<div class="pull-left">
			<div class="title">

			<h2>Data Outlet</h2>
		</div>
		<div class="pull-right">
			<a class="btn btn-success" href="{{ route('outlets.create') }}"> Buat Outlet Baru</a>
		</div>
		</div>
	</div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif

<table class="table table-bordered">

	<tr class="table-color-header">

		<th>No</th>
		<th>Nama Outlet</th>
		<th>Alamat</th>
		<th>No Telepon</th>
		<th width="280px">Action</th>
	</tr>
	@foreach ($outlets as $outlet)

	<tr>
		<td>{{ ++$i }}</td>
		<td>{{ $outlet->nama_outlet }}</td>
		<td>{{ $outlet->alamat }}</td>
		<td>{{ $outlet->no_telp }}</td>
	
	<td>
		<form class="center" action="{{ route('outlets.destroy',$outlet->id_outlet) }}" method="POST">

			<a class="btn btn-success" href="{{ route('outlets.show', $outlet->id_outlet) }}" >Show</a>

			<a class="btn btn-primary" href="{{ route('outlets.edit', $outlet->id_outlet) }}" >Edit</a>

			@csrf
			@method('DELETE')

			<button type="submit" class="btn btn-danger">Delete</button>

			

		</form>
		
	</td>

	</tr>

	@endforeach

</table>

{!! $outlets->links() !!}

</div>

@endsection

resources/views/outlet/show.blade.php
@extends('layouts.app')

@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif
<div class="container-fluid">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<div class="row">
	
	<div class="col-lg-12 margin-tb">
		
		<div class="text-center txt-tittle">
			
			<h2>Detail Outlet</h2>

		</div>

		<div class="float-left">
			
			<a class="btn btn-primary btn-back-detail-outlet" href="{{ route('outlets.index')}}">Back</a>

		</div>

	</div>
 
</div>

<div class="row row-left">
	
	<div class="col-xs-12 col-sm-12 col-md-6 mt-2">
		
		<div class="form-group txt-nama">
			
			<h2>Nama Outlet :</h2>

			<div class="txt-datmem-detout">

				<h2>{{ $outlet->nama_outlet }}</h2>
			</div>

		</div>

	</div>

	<div class="col-xs-12 col-sm-12 col-md-12">
		
		<div class="form-group txt-nama">
			
			<h2>Alamat :</h2>

			<div class="txt-datmem-detout">

				<h2>{{ $outlet->alamat }}</h2>

				</div>

		</div>

	</div>

	<div class="col-xs-12 col-sm-12 col-md-12">
		
		<div class="form-group txt-nama">
			
			<h2>No Telepon :</h2>

			<div class="txt-datmem-detout">

				<h2>{{ $outlet->no_telp }}</h2>
			</div>

		</div>

	</div>

</div>
</div>
<div class="container">
	<div class="row">
	<div class="col-lg-12 margin-tb">
		<div class="float-left">
			<div class="title">

			<h2>Data paket yang tersedia</h2>
		</div>
		<div class="float-left">
			<a class="btn btn-success" href="{{ route('paket.create') }}"> Buat paket Baru</a>
		</div>
		</div>
	</div>
</div>



<table class="table table-bordered">

	<tr class="table-color-header">

		<th>Jenis</th>
		<th>Nama Paket</th>
		<th>Harga</th>
		<th width="280px">Action</th>
	</tr>
	@foreach ($paket->where('id_outlet', $outlet->id_outlet) as $paketan)

	<tr>
		<td>{{ $paketan->jenis }}</td>
		<td>{{ $paketan->nama_paket }}</td>
		<td>{{ $paketan->harga }}</td>
	
	<td>
		<form class="center" action="{{ route('paket.destroy',$paketan->id_paket) }}" method="POST">

			<a class="btn btn-primary" href="{{ route('paket.edit', $paketan->id_paket) }}" >Edit</a>

			@csrf
			@method('DELETE')

			<button type="submit" class="btn btn-danger">Delete</button>

			

		</form>
		
	</td>

	</tr>

	@endforeach

</table>


</div>

@endsection